sudo: required
language: generic

services:
    - docker
before_install:
    - docker build -t raghavendra/my-react-app  -f Dockerfile.dev .

script:
    - docker run -e CI=true raghavendra/my-react-app npm run test


