sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ragpark/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true ragpark/docker-react-app npm run test