sudo: required
language: node_js

services:
  - docker

before_install:
  - docker build -t ragpark/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ragpark/docker-react npm run test